source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'

# RTC SDK
pod 'VolcEngineRTC', '3.54.0.557200'
pod 'VolcEngineRTC/ScreenCapture'

target 'veRTC Room' do
  platform :ios, '12.0'
  # 依赖 SDK
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  pod 'KVOController'
  
  # 基础组件
  # Basic components
  pod 'Core', :path => '../RTCSolution/Core'

  # 场景化源码
  # Scene source code
  # 登录
  pod 'LoginKit', :path => '../RTCSolution/APP/LoginKit'


  # 获取 RTS 登录信息
  pod 'veJoinRTSParams', :path => '../RTCSolution/APP/veJoinRTSParams'
  
  # 视频会议
  pod 'MeetingDemo', :path => '../RTCSolution/APP/MeetingDemo'
  
  # 教育小班课
  pod 'EduSmallClassDemo', :path => '../RTCSolution/APP/EduSmallClassDemo'
  
  # 教育大班课
  pod 'EduBigClassDemo', :path => '../RTCSolution/APP/EduBigClassDemo'
  
  # 白板
  pod 'VolcEngineWhiteboard', '1.6.2'

end

## 屏幕共享使用
target 'MeetingScreenShare' do
  platform :ios, '12.0'

end
